sudo: required
dist: trusty
notifications:
  email:
    on_success: always
    on_failure: always
env:
  matrix:
    - ROS_DISTRO="indigo"  USE_DEB="true"
    - ROS_DISTRO="kinetic" USE_DEB="true"
    - ROS_DISTRO="lunar"   USE_DEB="true"
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - source .ci_config/travis.sh
